apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: webapp
    apps.tanzu.vmware.com/workload-type: ecs
    apps.tanzu.vmware.com/has-tests: "true"
  name: webapp
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
    - name: gitops_ssh_secret
      value: git-ssh
  source:
    git:
      ref:
        branch: main
      url: https://github.com/mhoshi-vm/webapp-ecs03.git